# Site settings
title: Kevin Esmael Liu
description: "A lot of Everything?"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://kevinesmaell.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: kevin esmael liu
user_title: Lorem Ipsum - FrontEnd
email: kevinesmaell@outlook.com
twitter_username: 
github_username:  kevinesmaell
gplus_username:  
linkedin_public_url: kevin-liu-376653223 # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: 
profile_picture: https://data.whicdn.com/images/349537654/original.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: tags
      url: /tags
      key_trigger: 3
    - title: projects
      url: /about
      key_trigger: 4
  section_2:
    - title: github
      url: https://github.com/kevinesmaell
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: minecraft builds
    url: https://www.youtube.com/watch?v=x2fvHwCSGbk
  - name: cryptocurrency mining
    url: https://www.youtube.com/watch?v=8dAWgnmgcso
  - name: spotify reskins
    url: https://www.youtube.com/watch?v=rRhratE0KNk

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# pinned
pinned:
  - name: project catalog/directory
    url: https://kevinesmaell.github.io/about/